-- Xerago Intelligence Engine — MVP Initial Schema (MySQL 8.0+)
-- Version: db_v1.0.0
-- Engine: InnoDB, utf8mb4
-- Aligns with: docs/output_schema.md, docs/implementation/service-boundaries.md
--
-- Apply via Alembic baseline migration in Sprint 1.
-- UUIDs: CHAR(36) — generated by application or DEFAULT (UUID()) on MySQL 8.0.13+
-- Timestamps: DATETIME(6) — store UTC; session time_zone = '+00:00' recommended

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ─────────────────────────────────────────────────────────────────────────────
-- Source health (ingestion observability)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE source_health (
    source_id           VARCHAR(64) NOT NULL,
    last_success_at     DATETIME(6) NULL,
    last_attempt_at     DATETIME(6) NULL,
    last_error          TEXT NULL,
    failure_count       INT NOT NULL DEFAULT 0,
    lag_minutes         INT NULL,
    enabled             TINYINT(1) NOT NULL DEFAULT 1,
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (source_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- Ingest cursors (FreshRSS / GitHub poll state)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE ingest_cursors (
    source_id           VARCHAR(64) NOT NULL,
    cursor_value        TEXT NOT NULL,
    last_entry_id       VARCHAR(255) NULL,
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (source_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE repository_poll_state (
    repo_id             VARCHAR(255) NOT NULL,
    last_release_id     BIGINT NULL,
    last_release_tag    VARCHAR(128) NULL,
    last_polled_at      DATETIME(6) NULL,
    etag                VARCHAR(255) NULL,
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (repo_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- Raw artifacts (immutable ingest record)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE artifacts (
    artifact_id         CHAR(36) NOT NULL,
    source_id           VARCHAR(64) NOT NULL,
    entity_slug         VARCHAR(64) NULL,
    content_type        ENUM('article', 'github_release', 'research_paper', 'manual') NOT NULL DEFAULT 'article',
    canonical_url       TEXT NOT NULL,
    title               TEXT NOT NULL,
    body_text           MEDIUMTEXT NULL,
    body_html           MEDIUMTEXT NULL,
    content_hash        VARCHAR(64) NOT NULL,
    published_at        DATETIME(6) NOT NULL,
    ingested_at         DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    raw_metadata        JSON NOT NULL,
    github_repo_id      VARCHAR(255) NULL,
    github_release_tag  VARCHAR(128) NULL,
    github_release_id   BIGINT NULL,
    PRIMARY KEY (artifact_id),
    UNIQUE KEY uq_artifacts_canonical_url (canonical_url(768)),
    UNIQUE KEY uq_artifacts_source_hash (source_id, content_hash),
    KEY idx_artifacts_source_id (source_id),
    KEY idx_artifacts_published_at (published_at),
    KEY idx_artifacts_content_hash (content_hash),
    KEY idx_artifacts_github (github_repo_id, github_release_tag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- Dedup clusters
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE clusters (
    cluster_id          CHAR(36) NOT NULL,
    canonical_artifact_id CHAR(36) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (cluster_id),
    KEY idx_clusters_canonical (canonical_artifact_id),
    CONSTRAINT fk_clusters_canonical_artifact
        FOREIGN KEY (canonical_artifact_id) REFERENCES artifacts (artifact_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cluster_members (
    cluster_id          CHAR(36) NOT NULL,
    artifact_id         CHAR(36) NOT NULL,
    is_canonical        TINYINT(1) NOT NULL DEFAULT 0,
    added_at            DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (cluster_id, artifact_id),
    KEY idx_cluster_members_artifact (artifact_id),
    CONSTRAINT fk_cluster_members_cluster
        FOREIGN KEY (cluster_id) REFERENCES clusters (cluster_id) ON DELETE CASCADE,
    CONSTRAINT fk_cluster_members_artifact
        FOREIGN KEY (artifact_id) REFERENCES artifacts (artifact_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- Intelligence records (precomputed output)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE intelligence (
    intelligence_id     CHAR(36) NOT NULL,
    public_id           VARCHAR(32) NOT NULL,
    artifact_id         CHAR(36) NOT NULL,
    cluster_id          CHAR(36) NULL,
    status              ENUM('processing', 'published', 'suppressed') NOT NULL DEFAULT 'processing',
    is_canonical        TINYINT(1) NOT NULL DEFAULT 1,
    title               VARCHAR(300) NOT NULL,
    summary             TEXT NULL,
    why_it_matters      TEXT NULL,
    event_type_primary  VARCHAR(64) NULL,
    event_type_sub      VARCHAR(64) NULL,
    entity_slug         VARCHAR(64) NULL,
    entity_group        VARCHAR(32) NULL,
    entity_display_name VARCHAR(128) NULL,
    source_id           VARCHAR(64) NOT NULL,
    source_display_name VARCHAR(128) NULL,
    source_url          TEXT NOT NULL,
    source_trust_tier   CHAR(2) NOT NULL,
    strategic_score     SMALLINT NULL,
    impact_level        ENUM('Low', 'Medium', 'High', 'Strategic') NULL,
    employee_relevance  ENUM('broadcast', 'practice', 'specialist', 'archive') NULL,
    score_breakdown     JSON NULL,
    scoring_version     VARCHAR(32) NULL,
    promotion_trace     JSON NOT NULL,
    suppressed_reason   VARCHAR(64) NULL,
    classification_confidence DECIMAL(4, 3) NULL,
    published_at        DATETIME(6) NOT NULL,
    ingested_at         DATETIME(6) NOT NULL,
    enriched_at         DATETIME(6) NULL,
    scored_at           DATETIME(6) NULL,
    published_record_at DATETIME(6) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    github              JSON NULL,
    research            JSON NULL,
    PRIMARY KEY (intelligence_id),
    UNIQUE KEY uq_intelligence_public_id (public_id),
    UNIQUE KEY uq_intelligence_artifact (artifact_id),
    KEY idx_intelligence_feed (status, strategic_score, published_at),
    KEY idx_intelligence_entity (entity_slug, published_at),
    KEY idx_intelligence_published_at (published_at),
    KEY idx_intelligence_source (source_id),
    KEY idx_intelligence_cluster (cluster_id),
    CONSTRAINT fk_intelligence_artifact
        FOREIGN KEY (artifact_id) REFERENCES artifacts (artifact_id),
    CONSTRAINT fk_intelligence_cluster
        FOREIGN KEY (cluster_id) REFERENCES clusters (cluster_id),
    CONSTRAINT chk_intelligence_trust_tier
        CHECK (source_trust_tier IN ('T1', 'T2', 'T3')),
    CONSTRAINT chk_intelligence_score
        CHECK (strategic_score IS NULL OR (strategic_score >= 0 AND strategic_score <= 100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- Intelligence ↔ Xerago domains (many-to-many)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE intelligence_domains (
    intelligence_id     CHAR(36) NOT NULL,
    domain_slug         VARCHAR(64) NOT NULL,
    display_name        VARCHAR(128) NOT NULL,
    is_primary          TINYINT(1) NOT NULL DEFAULT 0,
    relevance_score     DECIMAL(4, 3) NULL,
    PRIMARY KEY (intelligence_id, domain_slug),
    KEY idx_intelligence_domains_slug (domain_slug),
    CONSTRAINT fk_intelligence_domains_intelligence
        FOREIGN KEY (intelligence_id) REFERENCES intelligence (intelligence_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Note: at most one is_primary per intelligence_id — enforced in application layer (MySQL has no partial unique index)

-- ─────────────────────────────────────────────────────────────────────────────
-- OSS version ledger (anti-repeat)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE repository_version_ledger (
    repo_id             VARCHAR(255) NOT NULL,
    version             VARCHAR(128) NOT NULL,
    intelligence_id     CHAR(36) NULL,
    surfaced_at         DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    semver_major        INT NULL,
    semver_minor        INT NULL,
    semver_patch        INT NULL,
    PRIMARY KEY (repo_id, version),
    KEY idx_version_ledger_repo (repo_id, surfaced_at),
    CONSTRAINT fk_version_ledger_intelligence
        FOREIGN KEY (intelligence_id) REFERENCES intelligence (intelligence_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- Pipeline runs (idempotency + debugging)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE pipeline_runs (
    run_id              CHAR(36) NOT NULL,
    artifact_id         CHAR(36) NOT NULL,
    intelligence_id     CHAR(36) NULL,
    stage               ENUM(
        'ingested', 'normalized', 'classified', 'deduped', 'gated',
        'enriched', 'scored', 'published', 'failed'
    ) NOT NULL,
    status              ENUM('running', 'completed', 'failed', 'retrying') NOT NULL DEFAULT 'running',
    celery_task_id      VARCHAR(255) NULL,
    idempotency_key     VARCHAR(255) NOT NULL,
    error_message       TEXT NULL,
    started_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    completed_at        DATETIME(6) NULL,
    metadata            JSON NOT NULL,
    PRIMARY KEY (run_id),
    UNIQUE KEY uq_pipeline_runs_idempotency (idempotency_key),
    KEY idx_pipeline_runs_artifact (artifact_id, started_at),
    CONSTRAINT fk_pipeline_runs_artifact
        FOREIGN KEY (artifact_id) REFERENCES artifacts (artifact_id),
    CONSTRAINT fk_pipeline_runs_intelligence
        FOREIGN KEY (intelligence_id) REFERENCES intelligence (intelligence_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- Enrichment audit (LLM calls)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE enrichment_runs (
    enrichment_id       CHAR(36) NOT NULL,
    intelligence_id     CHAR(36) NOT NULL,
    provider            VARCHAR(32) NOT NULL,
    model               VARCHAR(128) NULL,
    prompt_version      VARCHAR(32) NOT NULL,
    prompt_tokens       INT NULL,
    completion_tokens   INT NULL,
    latency_ms          INT NULL,
    success             TINYINT(1) NOT NULL,
    error_message       TEXT NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (enrichment_id),
    KEY idx_enrichment_runs_intelligence (intelligence_id, created_at),
    CONSTRAINT fk_enrichment_runs_intelligence
        FOREIGN KEY (intelligence_id) REFERENCES intelligence (intelligence_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- Related sources (corroboration — detail API)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE intelligence_related_sources (
    id                  CHAR(36) NOT NULL,
    intelligence_id     CHAR(36) NOT NULL,
    source_id           VARCHAR(64) NULL,
    source_name         VARCHAR(128) NULL,
    trust_tier          CHAR(2) NULL,
    url                 TEXT NOT NULL,
    published_at        DATETIME(6) NULL,
    added_at            DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_related_sources_intelligence (intelligence_id),
    CONSTRAINT fk_related_sources_intelligence
        FOREIGN KEY (intelligence_id) REFERENCES intelligence (intelligence_id) ON DELETE CASCADE,
    CONSTRAINT chk_related_sources_trust_tier
        CHECK (trust_tier IS NULL OR trust_tier IN ('T1', 'T2', 'T3'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- Research store (broad ingest; narrow promotion)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE research_artifacts (
    research_id         CHAR(36) NOT NULL,
    artifact_id         CHAR(36) NULL,
    source_id           VARCHAR(64) NOT NULL,
    paper_title         TEXT NULL,
    arxiv_id            VARCHAR(32) NULL,
    pwc_url             TEXT NULL,
    benchmarks          JSON NOT NULL,
    relevance_gate      VARCHAR(32) NULL,
    gate_passed         TINYINT(1) NOT NULL DEFAULT 0,
    promoted_intelligence_id CHAR(36) NULL,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (research_id),
    KEY idx_research_gate (gate_passed, created_at),
    CONSTRAINT fk_research_artifacts_artifact
        FOREIGN KEY (artifact_id) REFERENCES artifacts (artifact_id),
    CONSTRAINT fk_research_artifacts_intelligence
        FOREIGN KEY (promoted_intelligence_id) REFERENCES intelligence (intelligence_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ─────────────────────────────────────────────────────────────────────────────
-- Dead letter queue (failed tasks after max retries)
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE pipeline_dead_letters (
    id                  CHAR(36) NOT NULL,
    artifact_id         CHAR(36) NULL,
    stage               ENUM(
        'ingested', 'normalized', 'classified', 'deduped', 'gated',
        'enriched', 'scored', 'published', 'failed'
    ) NOT NULL,
    payload             JSON NOT NULL,
    error_message       TEXT NOT NULL,
    retry_count         INT NOT NULL DEFAULT 0,
    created_at          DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    resolved_at         DATETIME(6) NULL,
    PRIMARY KEY (id),
    KEY idx_dead_letters_artifact (artifact_id),
    CONSTRAINT fk_dead_letters_artifact
        FOREIGN KEY (artifact_id) REFERENCES artifacts (artifact_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
